[book]
authors = ["iamslash"]
language = "en"
src = "src"
title = "iamslash"

[build]
build-dir = "../book/en"

[output.html]
git-repository-url = "https://github.com/iamslash/iamslash.github.io"
site-url = "/en/"
